import { ethereum, Address, log, Bytes } from "@graphprotocol/graph-ts"
import { HorizonStaking } from "../../generated/HorizonStaking/HorizonStaking"
import { getOrCreateGraphNetwork, saveGraphNetwork } from "../entities/graphNetwork"
import { getOrCreateServiceProvider, saveServiceProvider } from "../entities/serviceProvider"
import { getOrCreateDelegationPool, saveDelegationPool } from "../entities/delegationPool"
import { config } from "../config"
import { NetworkConfig } from "../config/types"
import {
  encodeGetStake,
  encodeGetDelegationPool,
  decodeGetStakeResult,
  decodeGetDelegationPoolResult,
} from "../common/multicall"

// Batch size for multicall - balance between efficiency and gas limits
const MULTICALL_BATCH_SIZE = 100

/**
 * Runs once at startBlock via block handler with `filter: kind: once`.
 *
 * Seeds ServiceProvider entities for indexers that existed before Horizon launch
 * by reading their stake directly from the contract. Note that this "flattens"
 * all pre-Horizon activity into a single stake snapshot, i.e. stake deposits,
 * indexing reward and query fee stake gains, slashings, all get combined into
 * one stake amount which means detailed history pre-Horizon is effectively lost.
 *
 * Also seeds DelegationPool, Delegator, and Delegation entities for legacy delegations
 * that were auto-migrated to the Subgraph Service without emitting events.
 *
 * Address lists are generated by querying the legacy network subgraph at genesis
 * block (see packages/tools).
 */
export function handleHorizonGenesisBlock(block: ethereum.Block): void {
  migrateServiceProviders(block, config)
  migrateDelegationPools(block, config)
}

/**
 * Core migration logic extracted for testability.
 * Seeds ServiceProvider entities by reading stake from the contract using multicall.
 */
export function migrateServiceProviders(block: ethereum.Block, networkConfig: NetworkConfig): void {
  let graphNetwork = getOrCreateGraphNetwork()

  // Skip if no service providers to migrate
  if (networkConfig.serviceProviderAddresses.length == 0) {
    saveGraphNetwork(graphNetwork)
    return
  }

  let stakingContract = HorizonStaking.bind(networkConfig.horizonStakingAddress)
  let addresses = networkConfig.serviceProviderAddresses

  // Process in batches using multicall
  for (let batchStart = 0; batchStart < addresses.length; batchStart += MULTICALL_BATCH_SIZE) {
    let batchEnd = batchStart + MULTICALL_BATCH_SIZE
    if (batchEnd > addresses.length) {
      batchEnd = addresses.length
    }

    // Encode all getStake calls for this batch
    let calls: Bytes[] = []
    for (let i = batchStart; i < batchEnd; i++) {
      let address = Address.fromString(addresses[i])
      calls.push(encodeGetStake(address))
    }

    // Execute multicall
    let multicallResult = stakingContract.try_multicall(calls)
    if (multicallResult.reverted) {
      log.critical("Multicall failed for service provider batch starting at {}", [batchStart.toString()])
      continue
    }

    let results = multicallResult.value

    // Process results
    for (let i = 0; i < results.length; i++) {
      let address = Address.fromString(addresses[batchStart + i])
      let tokensStaked = decodeGetStakeResult(results[i])

      // Create service provider
      let sp = getOrCreateServiceProvider(address, block.number, block.timestamp)
      assert(sp.isNew, "Service provider already exists.")
      sp.entity.tokensStaked = tokensStaked
      sp.entity.tokensIdle = tokensStaked // No provisions at migration, so all stake is idle
      saveServiceProvider(sp.entity, block)

      // Update graph network totals
      graphNetwork.tokensStaked = graphNetwork.tokensStaked.plus(tokensStaked)
      graphNetwork.countServiceProviders += 1
    }
  }

  saveGraphNetwork(graphNetwork)
}

/**
 * Seeds DelegationPool entities using multicall.
 *
 * Legacy delegations were auto-migrated to Subgraph Service without events.
 * This function reads pool state from the contract to seed DelegationPools
 * and update ServiceProvider.tokensDelegated.
 *
 * Individual Delegator and Delegation entities are NOT seeded here - they are
 * lazy-initialized when delegators perform any action (delegate, undelegate, withdraw).
 */
export function migrateDelegationPools(block: ethereum.Block, networkConfig: NetworkConfig): void {
  // Skip if no delegation pools to migrate
  if (networkConfig.delegatedIndexerAddresses.length == 0) {
    return
  }

  let stakingContract = HorizonStaking.bind(networkConfig.horizonStakingAddress)
  let verifier = networkConfig.subgraphServiceAddress
  let graphNetwork = getOrCreateGraphNetwork()

  let indexerAddresses = networkConfig.delegatedIndexerAddresses

  // Seed DelegationPools using multicall
  for (let batchStart = 0; batchStart < indexerAddresses.length; batchStart += MULTICALL_BATCH_SIZE) {
    let batchEnd = batchStart + MULTICALL_BATCH_SIZE
    if (batchEnd > indexerAddresses.length) {
      batchEnd = indexerAddresses.length
    }

    // Encode all getDelegationPool calls for this batch
    let calls: Bytes[] = []
    for (let i = batchStart; i < batchEnd; i++) {
      let indexerAddress = Address.fromString(indexerAddresses[i])
      calls.push(encodeGetDelegationPool(indexerAddress, verifier))
    }

    // Execute multicall
    let multicallResult = stakingContract.try_multicall(calls)
    if (multicallResult.reverted) {
      log.warning("Multicall failed for delegation pool batch starting at {}", [batchStart.toString()])
      continue
    }

    let results = multicallResult.value

    // Process results
    for (let i = 0; i < results.length; i++) {
      let globalIndex = batchStart + i
      let indexerAddress = Address.fromString(indexerAddresses[globalIndex])
      let poolData = decodeGetDelegationPoolResult(results[i])
      let poolTokens = poolData[0]

      let indexerBytes = Bytes.fromHexString(indexerAddress.toHexString()) as Bytes
      let verifierBytes = Bytes.fromHexString(verifier.toHexString()) as Bytes

      // Create delegation pool
      let pool = getOrCreateDelegationPool(indexerBytes, verifierBytes, block.number, block.timestamp)
      assert(pool.isNew, "Delegation pool already exists.")
      pool.entity.tokens = poolData[0]
      pool.entity.shares = poolData[1]
      pool.entity.tokensThawing = poolData[2]

      // Set legacy indexing reward cut from config (parallel array)
      if (globalIndex < networkConfig.legacyIndexerRewardCuts.length) {
        pool.entity.legacyIndexingRewardCut = networkConfig.legacyIndexerRewardCuts[globalIndex]
      }

      saveDelegationPool(pool.entity, block)

      // Update service provider tokensDelegated - Note that this service provider might not exist
      let serviceProvider = getOrCreateServiceProvider(indexerBytes, block.number, block.timestamp)
      serviceProvider.entity.tokensDelegated = serviceProvider.entity.tokensDelegated.plus(poolTokens)
      saveServiceProvider(serviceProvider.entity, block)

      graphNetwork.countDelegationPools += 1
      graphNetwork.tokensDelegated = graphNetwork.tokensDelegated.plus(poolTokens)
    }
  }

  saveGraphNetwork(graphNetwork)
}
