import { ethereum, Address, log } from "@graphprotocol/graph-ts"
import { HorizonStaking } from "../../generated/HorizonStaking/HorizonStaking"
import { getOrCreateGraphNetwork } from "../entities/graphNetwork"
import { getOrCreateServiceProvider } from "../entities/serviceProvider"
import { config } from "../config"
import { NetworkConfig } from "../config/types"

/**
 * Runs once at startBlock via block handler with `filter: kind: once`.
 *
 * Seeds ServiceProvider entities for indexers that existed before Horizon launch
 * by reading their stake directly from the contract. Note that this "flattens"
 * all pre-Horizon activity into a single stake snapshot, i.e. stake deposits,
 * indexing reward and query fee stake gains, slashings, all get combined into
 * one stake amount which means detailed history pre-Horizon is effectively lost.
 *
 * Address list is generated by querying the legacy network subgraph at genesis
 * block (see scripts/fetch-indexers.sh).
 */
export function handleHorizonGenesisBlock(block: ethereum.Block): void {
  migrateServiceProviders(block, config)
}

/**
 * Core migration logic extracted for testability.
 * Seeds ServiceProvider entities by reading stake from the contract.
 */
export function migrateServiceProviders(block: ethereum.Block, networkConfig: NetworkConfig): void {
  let graphNetwork = getOrCreateGraphNetwork()

  // Skip if no service providers to migrate
  if (networkConfig.serviceProviderAddresses.length == 0) {
    graphNetwork.save()
    return
  }

  let stakingContract = HorizonStaking.bind(networkConfig.horizonStakingAddress)

  for (let i = 0; i < networkConfig.serviceProviderAddresses.length; i++) {
    let address = Address.fromString(networkConfig.serviceProviderAddresses[i])

    // Fetch stake from contract
    let stakeResult = stakingContract.try_getStake(address)
    if (stakeResult.reverted) {
      log.critical("Failed to fetch stake for service provider {}", [address.toHexString()])
    }

    let tokensStaked = stakeResult.value

    // Create service provider
    let serviceProvider = getOrCreateServiceProvider(address, block.number, block.timestamp)
    assert(serviceProvider.isNew, "Service provider already exists")
    serviceProvider.entity.tokensStaked = tokensStaked
    // TODO: Set tokensIdle and tokensProvisioned when provision handlers are implemented
    // let idleResult = stakingContract.try_getIdleStake(address)
    // serviceProvider.entity.tokensIdle = idleResult.value
    // serviceProvider.entity.tokensProvisioned = tokensStaked.minus(idleResult.value)
    serviceProvider.entity.save()

    // Update graph network totals
    graphNetwork.tokensStaked = graphNetwork.tokensStaked.plus(tokensStaked)
    graphNetwork.countServiceProviders += 1
  }

  graphNetwork.save()
}
