import { ethereum, Address, log } from "@graphprotocol/graph-ts"
import { HorizonStaking } from "../../generated/HorizonStaking/HorizonStaking"
import { getOrCreateGraphNetwork, saveGraphNetwork } from "../entities/graphNetwork"
import { getOrCreateServiceProvider, saveServiceProvider } from "../entities/serviceProvider"
import { config } from "../config"
import { NetworkConfig } from "../config/types"

/**
 * Runs once at startBlock via block handler with `filter: kind: once`.
 *
 * Seeds ServiceProvider entities for indexers that existed before Horizon launch
 * by reading their stake directly from the contract. Note that this "flattens"
 * all pre-Horizon activity into a single stake snapshot, i.e. stake deposits,
 * indexing reward and query fee stake gains, slashings, all get combined into
 * one stake amount which means detailed history pre-Horizon is effectively lost.
 *
 * Address list is generated by querying the legacy network subgraph at genesis
 * block (see scripts/fetch-indexers.sh).
 */
export function handleHorizonGenesisBlock(block: ethereum.Block): void {
  migrateServiceProviders(block, config)
}

/**
 * Core migration logic extracted for testability.
 * Seeds ServiceProvider entities by reading stake from the contract.
 */
export function migrateServiceProviders(block: ethereum.Block, networkConfig: NetworkConfig): void {
  let graphNetwork = getOrCreateGraphNetwork()

  // Skip if no service providers to migrate
  if (networkConfig.serviceProviderAddresses.length == 0) {
    saveGraphNetwork(graphNetwork)
    return
  }

  let stakingContract = HorizonStaking.bind(networkConfig.horizonStakingAddress)

  for (let i = 0; i < networkConfig.serviceProviderAddresses.length; i++) {
    let address = Address.fromString(networkConfig.serviceProviderAddresses[i])

    // Fetch stake from contract
    let stakeResult = stakingContract.try_getStake(address)
    if (stakeResult.reverted) {
      log.critical("Failed to fetch stake for service provider {}", [address.toHexString()])
    }

    let tokensStaked = stakeResult.value

    // Create service provider
    let sp = getOrCreateServiceProvider(address, block.number, block.timestamp)
    assert(sp.isNew, "Service provider already exists.")
    sp.entity.tokensStaked = tokensStaked
    sp.entity.tokensIdle = tokensStaked // No provisions at migration, so all stake is idle
    saveServiceProvider(sp.entity, block)

    // Update graph network totals
    graphNetwork.tokensStaked = graphNetwork.tokensStaked.plus(tokensStaked)
    graphNetwork.countServiceProviders += 1
  }

  saveGraphNetwork(graphNetwork)
}
